# Generated by Django 5.0 on 2024-02-20 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NikHospital', '0002_alter_booking_name_alter_login_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='age',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
